// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tarea.proto

package distribuidosproyecto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SituacionReq struct {
	NroEscuadra          string   `protobuf:"bytes,1,opt,name=nro_escuadra,json=nroEscuadra,proto3" json:"nro_escuadra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SituacionReq) Reset()         { *m = SituacionReq{} }
func (m *SituacionReq) String() string { return proto.CompactTextString(m) }
func (*SituacionReq) ProtoMessage()    {}
func (*SituacionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_506988d2dfe89877, []int{0}
}

func (m *SituacionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SituacionReq.Unmarshal(m, b)
}
func (m *SituacionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SituacionReq.Marshal(b, m, deterministic)
}
func (m *SituacionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SituacionReq.Merge(m, src)
}
func (m *SituacionReq) XXX_Size() int {
	return xxx_messageInfo_SituacionReq.Size(m)
}
func (m *SituacionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SituacionReq.DiscardUnknown(m)
}

var xxx_messageInfo_SituacionReq proto.InternalMessageInfo

func (m *SituacionReq) GetNroEscuadra() string {
	if m != nil {
		return m.NroEscuadra
	}
	return ""
}

type Termino struct {
	Termino              string   `protobuf:"bytes,1,opt,name=termino,proto3" json:"termino,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Termino) Reset()         { *m = Termino{} }
func (m *Termino) String() string { return proto.CompactTextString(m) }
func (*Termino) ProtoMessage()    {}
func (*Termino) Descriptor() ([]byte, []int) {
	return fileDescriptor_506988d2dfe89877, []int{1}
}

func (m *Termino) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Termino.Unmarshal(m, b)
}
func (m *Termino) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Termino.Marshal(b, m, deterministic)
}
func (m *Termino) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Termino.Merge(m, src)
}
func (m *Termino) XXX_Size() int {
	return xxx_messageInfo_Termino.Size(m)
}
func (m *Termino) XXX_DiscardUnknown() {
	xxx_messageInfo_Termino.DiscardUnknown(m)
}

var xxx_messageInfo_Termino proto.InternalMessageInfo

func (m *Termino) GetTermino() string {
	if m != nil {
		return m.Termino
	}
	return ""
}

type SituacionResp struct {
	Resuelta             string   `protobuf:"bytes,1,opt,name=resuelta,proto3" json:"resuelta,omitempty"`
	NroLab               string   `protobuf:"bytes,2,opt,name=NroLab,proto3" json:"NroLab,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SituacionResp) Reset()         { *m = SituacionResp{} }
func (m *SituacionResp) String() string { return proto.CompactTextString(m) }
func (*SituacionResp) ProtoMessage()    {}
func (*SituacionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_506988d2dfe89877, []int{2}
}

func (m *SituacionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SituacionResp.Unmarshal(m, b)
}
func (m *SituacionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SituacionResp.Marshal(b, m, deterministic)
}
func (m *SituacionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SituacionResp.Merge(m, src)
}
func (m *SituacionResp) XXX_Size() int {
	return xxx_messageInfo_SituacionResp.Size(m)
}
func (m *SituacionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SituacionResp.DiscardUnknown(m)
}

var xxx_messageInfo_SituacionResp proto.InternalMessageInfo

func (m *SituacionResp) GetResuelta() string {
	if m != nil {
		return m.Resuelta
	}
	return ""
}

func (m *SituacionResp) GetNroLab() string {
	if m != nil {
		return m.NroLab
	}
	return ""
}

func init() {
	proto.RegisterType((*SituacionReq)(nil), "grpc.SituacionReq")
	proto.RegisterType((*Termino)(nil), "grpc.Termino")
	proto.RegisterType((*SituacionResp)(nil), "grpc.SituacionResp")
}

func init() { proto.RegisterFile("proto/tarea.proto", fileDescriptor_506988d2dfe89877) }

var fileDescriptor_506988d2dfe89877 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xa9, 0xc8, 0x36, 0xaf, 0x9b, 0xb0, 0x08, 0x52, 0xfa, 0xa4, 0xf5, 0xa5, 0x88, 0xb4,
	0xfe, 0xf9, 0x02, 0x6a, 0xf1, 0x4d, 0x7c, 0xd8, 0x7c, 0xf2, 0x45, 0x92, 0x34, 0xcc, 0x0b, 0x6d,
	0x6e, 0x77, 0x93, 0x88, 0xbe, 0xf9, 0xd1, 0x65, 0x6d, 0x27, 0x0e, 0xdf, 0xce, 0xef, 0xe4, 0x70,
	0x92, 0x13, 0x98, 0xb7, 0x4c, 0x9e, 0x0a, 0x2f, 0xd9, 0xc8, 0xbc, 0xd3, 0x62, 0x7f, 0xc5, 0xad,
	0x4e, 0xaf, 0x61, 0xba, 0x44, 0x1f, 0xa4, 0x46, 0xb2, 0x0b, 0xb3, 0x16, 0x67, 0x30, 0xb5, 0x4c,
	0x6f, 0xc6, 0xe9, 0x20, 0x2b, 0x96, 0x71, 0x74, 0x1a, 0x65, 0x07, 0x8b, 0x43, 0xcb, 0xf4, 0x38,
	0x58, 0xe9, 0x39, 0x8c, 0x5f, 0x0c, 0x37, 0x68, 0x49, 0xc4, 0x30, 0xf6, 0xbd, 0x1c, 0x82, 0x5b,
	0x4c, 0x4b, 0x98, 0xfd, 0xe9, 0x75, 0xad, 0x48, 0x60, 0xc2, 0xc6, 0x05, 0x53, 0xfb, 0x6d, 0xe9,
	0x2f, 0x8b, 0x13, 0x18, 0x3d, 0x33, 0x3d, 0x49, 0x15, 0xef, 0x75, 0x27, 0x03, 0xdd, 0x7c, 0x47,
	0x70, 0x54, 0x1a, 0xeb, 0x59, 0xd6, 0x4b, 0xc3, 0x1f, 0xa8, 0x8d, 0xb8, 0x83, 0xf9, 0xbd, 0x62,
	0xe4, 0x92, 0x9a, 0x60, 0x51, 0x77, 0xfd, 0xe2, 0x38, 0xdf, 0x6c, 0xc9, 0x77, 0x2e, 0x4c, 0xc4,
	0x3f, 0x73, 0x9d, 0x45, 0x57, 0x91, 0xb8, 0x84, 0x49, 0xff, 0x7c, 0xc9, 0x62, 0xd6, 0x67, 0x86,
	0x39, 0xc9, 0x2e, 0x6e, 0xd2, 0x0f, 0x17, 0xaf, 0xd9, 0x0a, 0xfd, 0x7b, 0x50, 0xb9, 0xa6, 0xa6,
	0x90, 0x16, 0x95, 0xac, 0xe9, 0xb3, 0xa8, 0xd0, 0x79, 0x46, 0x15, 0xb0, 0x22, 0xd7, 0x32, 0x7d,
	0x19, 0xed, 0x49, 0x8d, 0xba, 0x8f, 0xbd, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff, 0x28, 0x27, 0x1b,
	0x0c, 0x6d, 0x01, 0x00, 0x00,
}
